# Generated by Django 5.0 on 2024-01-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph',
            field=models.CharField(max_length=20),
        ),
    ]
