# Generated by Django 5.0 on 2024-01-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
